version: 2.1
parameters:
  EnableDebugging:
    description: 'When `true`, debugging commands will run and output to terminal.'
    type: boolean
    default: false
  BuildModule:
    description: 'When `true`, all build commands will run.'
    type: boolean
    default: false
  BuildHelpFiles:
    description: 'When `true`, Help files will be built.'
    type: boolean
    default: true
  ReleaseType:
    description: 'Release Type. Accepted values [ Major, Minor, Patch ]'
    type: enum
    enum: ["Major", "Minor", "Patch"]
    default: "Patch"

orbs:
  win: circleci/windows@2.2.0
workflows:
  version: 2
  ci:
    jobs:
      - Setup
      - Build Modules:
          requires:
            - Setup
      - Build Help Files:
          requires:
            - Setup
jobs:
  Setup:
    executor: win/default
    steps:
      - setup
      - debugging
  Build Modules:
    executor: win/default
    steps:
      - attach_workspace:
          at: .
      - build-module
  Build Help Files:
    executor: win/default
    steps:
      - attach_workspace:
          at: .
      - build-helpfiles
commands:
  setup:
    steps:
      - checkout
      - run: echo << pipeline.git.branch >>
      - persist_to_workspace:
          root: .
          paths:
            - .
  debugging:
    steps:
      - when:
          condition:
            equal: [ true, << pipeline.parameters.EnableDebugging >> ]
          steps:
            - attach_workspace:
                at: .
            - run:
                name: Install PowerShell Core
                command: dotnet tool install --global PowerShell
            - run:
                name: Display Session Variables (For Debugging)
                shell: pwsh.exe
                command: |
                  ./PowerShell/Deploy/Get-SessionVariables.ps1
  build-module:
    steps:
      - when:
          condition:
            equal: [ true, << pipeline.parameters.BuildModule >> ]
          steps:
            - attach_workspace:
                at: .
            - run:
                name: Build Module
                command: |
                  $ErrorActionPreference = 'Stop'
                  ./PowerShell/Deploy/Get-Config.ps1 -GitSourceBranch << pipeline.git.branch >> -GitSourceRepo << pipeline.project.git_url >> -ReleaseType << pipeline.parameters.ReleaseType >>
                  ./PowerShell/Deploy/Build-Module.ps1
  build-helpfiles:
    steps:
      - when:
          condition:
            equal: [ true, << pipeline.parameters.BuildHelpFiles >> ]
          steps:
            - attach_workspace:
               at: .
            - run:
               name: Build Help Files
               command: |
                 $ErrorActionPreference = 'Stop'
                 ./PowerShell/Deploy/Build-HelpFiles.ps1 -ModuleName JumpCloud -ModulePath "./PowerShell/JumpCloud Module"