version: 2.1
parameters:
  EnableDebugging:
    description: 'When `true`, debugging commands will run and output to terminal.'
    type: boolean
    default: false
  BuildModule:
    description: 'When `true`, all build commands will run.'
    type: boolean
    default: true

orbs:
  win: circleci/windows@2.2.0
workflows:
  version: 2
  ci:
    jobs:
      - Setup
      - Build Modules:
          requires:
            - Setup
jobs:
  Setup:
    executor: win/default
    steps:
      - setup
      - debugging
  Build Modules:
    executor: win/default
    steps:
      - build-module
commands:
  setup:
    steps:
      - checkout
      - run: echo << pipeline.git.branch >>
      - persist_to_workspace:
          root: .
          paths:
            - .
  debugging:
    steps:
      - when:
          condition:
            equal: [ true, << pipeline.parameters.EnableDebugging >> ]
          steps:
            - attach_workspace:
                at: .
            - run:
                name: Install PowerShell Core
                command: dotnet tool install --global PowerShell
            - run:
                name: Display Session Variables (For Debugging)
                shell: pwsh.exe
                command: |
                  ./PowerShell/Deploy/Get-SessionVariables.ps1
  build-module:
    steps:
      - when:
          condition:
            equal: [ true, << pipeline.parameters.BuildModule >> ]
          steps:
            - attach_workspace:
                at: .
            - run:
                name: Build Module
                shell: pwsh.exe
                command: |
                  ./PowerShell/Deploy/Build-Module.ps1  