version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.2
workflows:
  version: 2
  check-updated-files:
    jobs:
    - path-filtering/filter:
        mapping: |
          PowerShell/(?!jumpcloud commands gallery|jumpcloud.office.365.sso).* PowerShellModified true
        base-revision: master
        config-path: .circleci/workflows.yml